<?php
$data = array (
  0 => 
  array (
    'cat_id' => '7',
    'cat_name' => '户外',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '卧室',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 80,
  ),
  2 => 
  array (
    'cat_id' => '14',
    'cat_name' => '餐厅',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 17,
  ),
  3 => 
  array (
    'cat_id' => '10',
    'cat_name' => '其他',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 21,
  ),
  4 => 
  array (
    'cat_id' => '3',
    'cat_name' => '厨卫',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  5 => 
  array (
    'cat_id' => '9',
    'cat_name' => '套装',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '书房',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 13,
  ),
  7 => 
  array (
    'cat_id' => '1',
    'cat_name' => '客厅',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 104,
  ),
  8 => 
  array (
    'cat_id' => '11',
    'cat_name' => '儿童',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
  ),
);
?>